# Generated by Django 2.0.2 on 2018-05-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yanzheng',
            name='class_a',
            field=models.ForeignKey(default=1, on_delete=True, to='user.Class'),
            preserve_default=False,
        ),
    ]
